services:
  postgres:
    image: postgres:16
    container_name: reservation-postgres
    environment:
      POSTGRES_DB: reservation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - reservation_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d reservation_db"]
      interval: 10s
      timeout: 5s
      retries: 8

  reservation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reservation_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
      APP_SECURITY_ENABLED: "false"
      INTEGRATION_SERVICES_ENABLED: "true"
      INTEGRATION_USER_BY_ID_URL_TEMPLATE: http://host.docker.internal:8893/api/users/{id}
      INTEGRATION_SALON_BY_ID_URL_TEMPLATE: http://host.docker.internal:8894/api/salons/{id}
      INTEGRATION_HAIRDRESSER_BY_ID_URL_TEMPLATE: http://host.docker.internal:8894/api/hairdressers/{id}
      HTTP_PORT: 8896
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8896:8896"

volumes:
  reservation_pgdata:
