spring:
  cloud:
    discovery:
      enabled: ${SPRING_CLOUD_DISCOVERY_ENABLED:true}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/reservation_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI:http://auth-service:8080/realms/coifure}

integration:
  services:
    enabled: ${INTEGRATION_SERVICES_ENABLED:true}

app:
  security:
    enabled: ${APP_SECURITY_ENABLED:true}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
