server.port=${SERVER_PORT:8894}

spring.application.name=SALON-SERVICE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55432/salon_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:salon}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:salon}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
spring.datasource.hikari.initialization-fail-timeout=0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}

management.endpoints.web.exposure.include=health,info
