spring.autoconfigure.exclude=

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55432/salon_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:salon}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:salon}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=true
