spring.application.name=discovery-server
server.port=${DISCOVERY_SERVER_PORT:8762}

spring.security.user.name=admin
spring.security.user.password=admin123

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:${server.port}/eureka/}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP_ADDRESS:true}

eureka.server.enable-self-preservation=false

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
